### ISSUE TITLE
Database sql for undead ?

### ISSUE THREAD

**Issue by niodamian** [kibook/redm-undead#1]
you forgot to put the database or sql for undead ! otherwise will give errors with sql all the time

**Comment by kibook** [comment]
Use of a database is optional, and can be disabled  by setting `Config.enableDb` to false in config.lua. The database is currently only used to keep track of the number of undead players have killed for the scoreboard.

If you do want to use the database, you will need [ghmattimysql](https://github.com/GHMatti/ghmattimysql) and a MySQL database setup on your server.

There is no SQL file required to execute, as the server script will create the table when first run: https://github.com/kibook/redm-undead/blob/7e63a89aaecf802dc090de34f9ccbb918904c672/server.lua#L242
