### ISSUE TITLE
ERROR ?

### ISSUE THREAD

**Issue by niodamian** [kibook/redm-undead#2]
![20210730132610_1](https://user-images.githubusercontent.com/41478467/127639998-dc697229-dec4-4111-9dd1-ac9bb33c7c36.jpg)

**Comment by kibook** [comment]
This resource has a few dependencies:
- [uiprompt](https://github.com/kibook/redm-uiprompt)
- [uifeed](https://github.com/kibook/redm-uifeed)
- [ghmattimysql](https://github.com/GHMatti/ghmattimysql) (only if you want to use the database features)

I'll add a README detailing this, and also add these as actual dependencies in `fxmanifest.lua`.

**Comment by kibook** [comment]
4b7647e9d970349acad27b292bafdd0174511d37 adds the dependencies in fxmanifest.lua.
a8fc04fec685321806cb308a5aca62abc8d7ab40 adds a README with links to the dependencies.
